import { describe, expect, it } from 'vitest';
import type { Database } from './types.js';

describe('Database types', () => {
  it('includes all documented table groups', () => {
    const keys: (keyof Database)[] = [
      'user',
      'session',
      'account',
      'verification',
      'passkey',
      'user_security_event',
      'organisation',
      'organisation_member',
      'project',
      'project_member',
      'project_repository',
      'project_claim',
      'project_contact',
      'project_feature_mode',
      'project_review',
      'project_status_history',
      'stripe_connected_account',
      'stripe_capability_snapshot',
      'stripe_customer_binding',
      'stripe_product_binding',
      'stripe_price_binding',
      'stripe_event',
      'payment',
      'payment_allocation',
      'refund',
      'payment_dispute',
      'subscription',
      'subscription_period',
      'provider_balance_transaction',
      'reconciliation_run',
      'reconciliation_difference',
      'checkout_intent',
      'tier',
      'tier_price',
      'tier_reward',
      'entitlement',
      'post',
      'post_revision',
      'post_visibility_rule',
      'post_attachment',
      'supporter_public_profile',
      'supporter_message_thread',
      'supporter_message',
      'project_goal',
      'discord_connection',
      'discord_guild',
      'discord_role_mapping',
      'discord_role_assignment',
      'api_key',
      'webhook_endpoint',
      'webhook_delivery',
      'custom_domain',
      'email_delivery',
      'object_asset',
      'audit_event',
      'admin_case',
      'abuse_report',
      'job',
      'outbox_event',
      'ledger_account_binding',
      'ledger_posting_intent',
      'ledger_posting_result',
      'metric_event_hourly',
      'project_metric_daily',
      'platform_metric_daily',
    ];

    const tableSet = new Set<string>(keys);
    expect(tableSet.size).toBe(65);
  });
});
