/* Hallmark · admin workbench surfaces · restrained utility, clear evidence hierarchy */

import * as stylex from '@stylexjs/stylex';
import { paperlight } from '@oss-tips/design-tokens/paperlight.stylex';

export const admin = stylex.create({
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space6,
    marginInline: 'auto',
    maxWidth: paperlight.dashboardMax,
    minWidth: 0,
    width: '100%',
  },
  operatorBar: {
    alignItems: 'baseline',
    backgroundColor: paperlight.surface,
    borderColor: paperlight.info,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexWrap: 'wrap',
    gap: `${paperlight.space1} ${paperlight.space4}`,
    paddingBlock: paperlight.space3,
    paddingInline: paperlight.space4,
  },
  operatorBarWarning: {
    borderColor: paperlight.ochre,
  },
  operatorBarDanger: {
    borderColor: paperlight.danger,
  },
  operatorContext: {
    color: paperlight.ink,
    fontFamily: paperlight.uiFont,
    fontSize: '0.9375rem',
    fontWeight: 600,
    minWidth: 0,
    margin: 0,
    overflowWrap: 'anywhere',
  },
  operatorDetail: {
    color: paperlight.inkMuted,
    flexBasis: '100%',
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textSm,
    margin: 0,
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  toolbar: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
    justifyContent: 'space-between',
  },
  row: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
  },
  grid2: {
    display: 'grid',
    gap: paperlight.space6,
    gridTemplateColumns: 'minmax(0, 1fr)',
    '@media (min-width: 72rem)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  grid3: {
    display: 'grid',
    gap: paperlight.space4,
    gridTemplateColumns: 'minmax(0, 1fr)',
    '@media (min-width: 44rem)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    '@media (min-width: 72rem)': {
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    },
  },
  surface: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    padding: paperlight.space5,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
    minWidth: 0,
  },
  sectionHeading: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: paperlight.textXl,
    fontWeight: 500,
    lineHeight: 1.15,
    margin: 0,
  },
  tableWrap: {
    minWidth: 0,
    maxWidth: '100%',
    overflowX: 'auto',
    width: '100%',
  },
  footnote: {
    color: paperlight.inkMuted,
    fontSize: paperlight.textSm,
    lineHeight: 1.45,
    margin: 0,
  },
  select: {
    appearance: 'auto',
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    cursor: 'pointer',
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textMd,
    minHeight: paperlight.touchTarget,
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space3,
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': paperlight.motionReduced,
    },
    transitionProperty: 'border-color, color, transform',
    transitionTimingFunction: paperlight.easeOut,
    width: '100%',
    ':active': {
      transform: 'translateY(1px) scale(0.99)',
    },
    '@media (prefers-reduced-motion: reduce)': {
      ':active': {
        transform: 'none',
      },
    },
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.58,
    },
  },
  state: {
    alignItems: 'flex-start',
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
    maxWidth: '48rem',
    minWidth: 0,
    padding: paperlight.space6,
  },
  stateError: {
    borderColor: paperlight.danger,
  },
  stateForbidden: {
    borderColor: paperlight.info,
  },
  stateTitle: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: paperlight.textXl,
    fontWeight: 500,
    lineHeight: 1.15,
    margin: 0,
  },
  stateMessage: {
    color: paperlight.inkMuted,
    lineHeight: 1.45,
    margin: 0,
    maxWidth: '42rem',
    overflowWrap: 'anywhere',
  },

  responsiveTable: {
    minWidth: 0,
    width: '100%',
  },
  responsiveTableWide: {
    minWidth: 0,
    '@media (max-width: 71.99rem)': {
      display: 'none',
    },
  },
  responsiveTableNarrow: {
    display: 'none',
    gap: paperlight.space3,
    '@media (max-width: 71.99rem)': {
      display: 'grid',
    },
  },
  responsiveTableCaption: {
    color: paperlight.inkMuted,
    fontSize: paperlight.textSm,
    lineHeight: 1.45,
    margin: 0,
  },
  responsiveTableCard: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'grid',
    gap: paperlight.space3,
    minWidth: 0,
    padding: paperlight.space4,
  },
  responsiveTableCell: {
    alignItems: 'start',
    display: 'grid',
    gap: paperlight.space3,
    gridTemplateColumns: 'minmax(5rem, 32%) minmax(0, 1fr)',
    minWidth: 0,
  },
  responsiveTableLabel: {
    color: paperlight.inkMuted,
    fontSize: paperlight.textSm,
    fontWeight: 600,
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  responsiveTableValue: {
    fontVariantNumeric: 'tabular-nums',
    margin: 0,
    minWidth: 0,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
});
