/* Hallmark · pre-emit critique: P5 H5 E4 S5 R5 V4
 * Funding composites · Paperlight semantic styles · no page-specific selectors
 */

import * as stylex from '@stylexjs/stylex';
import { paperlight } from '@oss-tips/design-tokens/paperlight.stylex';

const tierCheckDraw = stylex.keyframes({
  from: { strokeDashoffset: 20 },
  to: { strokeDashoffset: 0 },
});

const amountChange = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(4px)' },
  to: { opacity: 1, transform: 'translateY(0)' },
});

export const funding = stylex.create({
  amountSelector: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    fontFamily: paperlight.uiFont,
    fontSize: '1rem',
    lineHeight: 1.5,
    gap: paperlight.space4,
    padding: paperlight.space6,
  },
  amountSelectorEmbedded: {
    backgroundColor: 'transparent',
    borderStyle: 'none',
    borderWidth: 0,
    padding: 0,
  },
  amountHeading: {
    fontFamily: paperlight.displayFont,
    fontSize: '1.25rem',
    fontWeight: 500,
    lineHeight: 1.1,
    margin: 0,
  },
  amountCadenceLabel: {
    color: paperlight.ink,
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: 600,
    marginBottom: paperlight.space2,
  },
  cadenceGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
  },
  cadenceOption: {
    alignItems: 'center',
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.inkMuted,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
    fontWeight: 600,
    justifyContent: 'center',
    minHeight: paperlight.touchTarget,
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space4,
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, color',
    transitionTimingFunction: paperlight.easeOut,
    '@media (hover: hover)': {
      ':hover': {
        borderColor: paperlight.borderStrong,
        color: paperlight.ink,
      },
    },
  },
  cadenceOptionSelected: {
    backgroundColor: paperlight.surfaceRaised,
    borderColor: paperlight.forest,
    color: paperlight.ink,
  },
  controlDisabled: {
    cursor: 'not-allowed',
    pointerEvents: 'none',
  },
  presets: {
    display: 'grid',
    gap: paperlight.space2,
    gridTemplateColumns: {
      default: 'repeat(4, minmax(0, 1fr))',
      '@media (max-width: 43.99rem)': 'repeat(2, minmax(0, 1fr))',
    },
  },
  preset: {
    alignItems: 'center',
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: paperlight.displayFont,
    fontSize: '1rem',
    fontVariantNumeric: 'tabular-nums',
    justifyContent: 'center',
    minHeight: paperlight.touchTarget,
    paddingInline: paperlight.space2,
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color',
    transitionTimingFunction: paperlight.easeOut,
    '@media (hover: hover)': {
      ':hover': {
        borderColor: paperlight.borderStrong,
      },
    },
  },
  presetSelected: {
    backgroundColor: paperlight.surfaceRaised,
    borderColor: paperlight.forest,
  },
  customField: {
    marginTop: paperlight.space2,
  },
  amountSummary: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    margin: 0,
  },
  amountSummaryValue: {
    color: paperlight.ink,
    fontWeight: 700,
    animationName: amountChange,
    animationDuration: {
      default: '140ms',
      '@media (prefers-reduced-motion: reduce)': '0.01ms',
    },
    animationFillMode: 'both',
    animationTimingFunction: paperlight.easeOut,
  },
  feedback: {
    color: paperlight.danger,
    fontSize: '0.875rem',
    margin: 0,
  },
  busy: {
    cursor: 'wait',
  },

  feeDisclosure: {
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    fontSize: '0.875rem',
    gap: paperlight.space2,
    padding: paperlight.space4,
  },
  feeHeading: {
    fontWeight: 700,
    margin: 0,
  },
  feeRow: {
    alignItems: 'baseline',
    display: 'flex',
    gap: paperlight.space4,
    justifyContent: 'space-between',
  },
  feeList: {
    margin: 0,
  },
  feeRowLabel: {
    color: paperlight.inkMuted,
  },
  feeRowValue: {
    color: paperlight.ink,
    fontVariantNumeric: 'tabular-nums',
    margin: 0,
    textAlign: 'end',
  },
  feeMeta: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
  },
  feeTotal: {
    borderTopColor: paperlight.border,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    fontWeight: 700,
    marginTop: paperlight.space2,
    paddingTop: paperlight.space2,
  },
  feeNote: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    lineHeight: 1.45,
    marginBlockEnd: 0,
    marginBlockStart: paperlight.space2,
    marginInline: 0,
  },

  tierCard: {
    alignItems: 'stretch',
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 2,
    color: paperlight.ink,
    cursor: 'default',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: paperlight.uiFont,
    fontSize: '1rem',
    lineHeight: 1.5,
    minHeight: '100%',
    minWidth: 0,
    padding: paperlight.space5,
    textAlign: 'start',
    transitionDuration: {
      default: paperlight.motionNormal,
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color',
    transitionTimingFunction: paperlight.easeOut,
    '@media (hover: hover)': {
      ':hover': {
        borderColor: paperlight.borderStrong,
      },
    },
  },
  tierCardSelected: {
    backgroundColor: paperlight.surfaceRaised,
    borderColor: paperlight.forest,
  },
  tierCardDisabled: {
    cursor: 'not-allowed',
    opacity: 0.58,
    pointerEvents: 'none',
  },
  tierCardError: {
    borderColor: paperlight.danger,
  },
  tierSelect: {
    alignItems: 'center',
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    cursor: 'pointer',
    display: 'flex',
    flexWrap: 'wrap',
    fontFamily: paperlight.uiFont,
    fontSize: '1rem',
    gap: paperlight.space3,
    justifyContent: 'space-between',
    lineHeight: 1.4,
    minHeight: paperlight.touchTarget,
    minWidth: 0,
    overflowWrap: 'anywhere',
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space3,
    textAlign: 'start',
    width: '100%',
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color, color',
    transitionTimingFunction: paperlight.easeOut,
    '@media (hover: hover)': {
      ':hover': {
        borderColor: paperlight.borderStrong,
      },
    },
  },
  tierSelectSelected: {
    backgroundColor: paperlight.surfaceRaised,
    borderColor: paperlight.forest,
  },
  tierTop: {
    alignItems: 'flex-start',
    display: 'flex',
    gap: paperlight.space3,
    justifyContent: 'space-between',
    marginBottom: paperlight.space2,
  },
  tierName: {
    fontSize: '1rem',
    fontWeight: 700,
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  tierBadges: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
    justifyContent: 'flex-end',
    maxWidth: '100%',
    minWidth: 0,
  },
  tierBadge: {
    backgroundColor: paperlight.surfaceRaised,
    borderColor: paperlight.ochre,
    borderRadius: paperlight.radiusRound,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    fontSize: '0.875rem',
    fontWeight: 700,
    paddingBlock: paperlight.space1,
    paddingInline: paperlight.space2,
  },
  tierCheck: {
    color: paperlight.forest,
    display: 'inline-flex',
  },
  tierCheckPath: {
    strokeDasharray: 20,
    strokeDashoffset: 20,
    animationName: tierCheckDraw,
    animationDuration: {
      default: '180ms',
      '@media (prefers-reduced-motion: reduce)': '0.01ms',
    },
    animationFillMode: 'forwards',
    animationTimingFunction: paperlight.easeOut,
  },
  tierDescription: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    lineHeight: 1.45,
    marginBlockEnd: paperlight.space3,
    marginBlockStart: 0,
    marginInline: 0,
  },
  tierPrice: {
    fontFamily: paperlight.displayFont,
    fontSize: '1.5rem',
    fontVariantNumeric: 'tabular-nums',
    lineHeight: 1.1,
  },
  tierCadence: {
    color: paperlight.inkMuted,
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
  },
  tierLimit: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    marginBlockEnd: 0,
    marginBlockStart: paperlight.space2,
    marginInline: 0,
  },
  tierRewards: {
    color: paperlight.inkMuted,
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space1,
    marginBlockEnd: 0,
    marginBlockStart: paperlight.space3,
    marginInline: 0,
    paddingInlineStart: paperlight.space4,
    '::marker': {
      color: paperlight.moss,
    },
  },
  tierError: {
    color: paperlight.danger,
    fontSize: '0.875rem',
    marginBlockEnd: 0,
    marginBlockStart: paperlight.space3,
    marginInline: 0,
  },

  composer: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space5,
    padding: paperlight.space6,
  },
  composerTierRow: {
    display: 'grid',
    gap: paperlight.space2,
    gridTemplateColumns: 'repeat(auto-fit, minmax(8rem, 1fr))',
  },
  composerTier: {
    alignItems: 'flex-start',
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space1,
    justifyContent: 'center',
    minHeight: paperlight.touchTarget,
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space3,
    textAlign: 'start',
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionProperty: 'background-color, border-color',
    transitionTimingFunction: paperlight.easeOut,
    '@media (hover: hover)': {
      ':hover': {
        borderColor: paperlight.borderStrong,
      },
    },
  },
  composerTierSelected: {
    backgroundColor: paperlight.surfaceRaised,
    borderColor: paperlight.forest,
  },
  composerTierName: {
    fontSize: '0.875rem',
    fontWeight: 700,
  },
  composerTierPrice: {
    fontFamily: paperlight.displayFont,
    fontVariantNumeric: 'tabular-nums',
  },
  tipField: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space2,
  },
  tipLabel: {
    fontSize: '0.875rem',
    fontWeight: 600,
  },
  tipHelp: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
  },
  tipPresets: {
    display: 'grid',
    gap: paperlight.space2,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
  },
  tipInput: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    fontFamily: paperlight.uiFont,
    fontSize: '1rem',
    minHeight: paperlight.touchTarget,
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space3,
    width: '100%',
  },
  recognition: {
    borderTopColor: paperlight.border,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
    paddingTop: paperlight.space5,
  },
  recognitionHeading: {
    fontFamily: paperlight.displayFont,
    fontSize: '1.125rem',
    fontWeight: 500,
    margin: 0,
  },
  recognitionFields: {
    display: 'grid',
    gap: paperlight.space3,
    gridTemplateColumns: 'repeat(auto-fit, minmax(12rem, 1fr))',
  },
  recognitionMessage: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    fontFamily: paperlight.uiFont,
    fontSize: '1rem',
    lineHeight: 1.5,
    minHeight: '6rem',
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space3,
    resize: 'vertical',
    width: '100%',
  },
  recognitionChecks: {
    display: 'grid',
    gap: paperlight.space2,
  },
  recognitionCheck: {
    alignItems: 'center',
    display: 'flex',
    gap: paperlight.space2,
    minHeight: paperlight.touchTarget,
  },
  recognitionCheckbox: {
    accentColor: paperlight.forest,
    blockSize: '1.125rem',
    inlineSize: '1.125rem',
  },
  composerSubmit: {
    width: '100%',
  },

  wall: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
  },
  wallHeading: {
    fontFamily: paperlight.displayFont,
    fontSize: '1.125rem',
    fontWeight: 500,
    margin: 0,
  },
  wallList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
    listStyleType: 'none',
    margin: 0,
    padding: 0,
  },
  wallChip: {
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusRound,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    fontSize: '0.875rem',
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space3,
  },
  wallAmount: {
    color: paperlight.inkMuted,
  },
  wallMessage: {
    color: paperlight.inkMuted,
    display: 'block',
    fontSize: '0.875rem',
    marginTop: paperlight.space1,
    maxWidth: '32rem',
    overflowWrap: 'anywhere',
  },
  wallPrivate: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    margin: 0,
  },

  thread: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    overflow: 'hidden',
  },
  threadHeader: {
    backgroundColor: paperlight.canvasSubtle,
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBlock: paperlight.space4,
    paddingInline: paperlight.space5,
  },
  threadHeaderRow: {
    alignItems: 'baseline',
    display: 'flex',
    flexWrap: 'wrap',
    columnGap: paperlight.space4,
    justifyContent: 'space-between',
    rowGap: paperlight.space2,
  },
  threadHeaderActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
    marginTop: paperlight.space3,
  },
  threadSubject: {
    fontSize: '1rem',
    fontWeight: 700,
  },
  threadMeta: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
  },
  threadMessage: {
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    paddingBlock: paperlight.space4,
    paddingInline: paperlight.space5,
  },
  threadMessageInternal: {
    backgroundColor: paperlight.surfaceRaised,
  },
  threadMessageSupporter: {
    backgroundColor: paperlight.surface,
  },
  threadMessageHead: {
    alignItems: 'baseline',
    display: 'flex',
    flexWrap: 'wrap',
    columnGap: paperlight.space4,
    justifyContent: 'space-between',
    marginBottom: paperlight.space2,
    rowGap: paperlight.space2,
  },
  threadAuthor: {
    fontSize: '0.875rem',
    fontWeight: 700,
  },
  threadTime: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
  },
  threadBody: {
    margin: 0,
    overflowWrap: 'anywhere',
  },
  internalBadge: {
    backgroundColor: paperlight.surfaceRaised,
    borderColor: paperlight.ochre,
    borderRadius: paperlight.radiusRound,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    display: 'inline-flex',
    fontSize: '0.875rem',
    fontWeight: 700,
    marginTop: paperlight.space2,
    paddingBlock: paperlight.space1,
    paddingInline: paperlight.space2,
  },
  threadFooter: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
    paddingBlock: paperlight.space4,
    paddingInline: paperlight.space5,
  },
  threadActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
  },
  threadReport: {
    borderTopColor: paperlight.border,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
    paddingTop: paperlight.space3,
  },
  threadStatus: {
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    margin: 0,
    paddingBlock: paperlight.space3,
    paddingInline: paperlight.space3,
  },
});
