/* Hallmark · post editor · compact authoring surface with an honest preview */

import * as stylex from '@stylexjs/stylex';
import { paperlight } from '@oss-tips/design-tokens/paperlight.stylex';

export const postEditorStyles = stylex.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space2,
    minWidth: 0,
  },
  label: {
    color: paperlight.ink,
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textSm,
    fontWeight: 650,
  },
  help: {
    color: paperlight.inkMuted,
    fontSize: paperlight.textSm,
    lineHeight: 1.4,
    margin: 0,
  },
  toolbar: {
    alignItems: 'center',
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
    padding: paperlight.space2,
  },
  toolbarGroup: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space1,
  },
  toolbarButton: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusSm,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    cursor: 'pointer',
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textSm,
    fontWeight: 650,
    minHeight: paperlight.touchTarget,
    paddingInline: paperlight.space3,
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': paperlight.motionReduced,
    },
    transitionProperty: 'background-color, border-color, color, transform',
    transitionTimingFunction: paperlight.easeOut,
    '@media (hover: hover)': {
      ':hover': {
        borderColor: paperlight.forest,
      },
    },
    ':active': {
      transform: 'translateY(1px) scale(0.99)',
    },
    '@media (prefers-reduced-motion: reduce)': {
      ':active': {
        transform: 'none',
      },
    },
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.55,
    },
  },
  toolbarButtonActive: {
    backgroundColor: paperlight.forest,
    borderColor: paperlight.forest,
    color: paperlight.onForest,
  },
  languageLabel: {
    alignItems: 'center',
    color: paperlight.inkMuted,
    display: 'inline-flex',
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textSm,
    gap: paperlight.space1,
    marginInlineStart: 'auto',
  },
  languageSelect: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusSm,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    fontFamily: paperlight.monoFont,
    fontSize: paperlight.textSm,
    minHeight: paperlight.touchTarget,
    paddingInline: paperlight.space2,
    cursor: 'pointer',
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': paperlight.motionReduced,
    },
    transitionProperty: 'border-color, color, transform',
    transitionTimingFunction: paperlight.easeOut,
    ':active': {
      transform: 'translateY(1px) scale(0.99)',
    },
    '@media (prefers-reduced-motion: reduce)': {
      ':active': {
        transform: 'none',
      },
    },
  },
  source: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    boxSizing: 'border-box',
    color: paperlight.ink,
    fontFamily: paperlight.monoFont,
    fontSize: '0.9375rem',
    lineHeight: 1.6,
    minHeight: '18rem',
    padding: paperlight.space4,
    resize: 'vertical',
    width: '100%',
  },
  preview: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    minHeight: '18rem',
    overflowWrap: 'anywhere',
    padding: paperlight.space5,
  },
  previewMeta: {
    alignItems: 'center',
    borderBlockEnd: `1px solid ${paperlight.border}`,
    color: paperlight.inkMuted,
    display: 'flex',
    flexWrap: 'wrap',
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textSm,
    gap: paperlight.space2,
    justifyContent: 'space-between',
    marginBlockEnd: paperlight.space4,
    paddingBlockEnd: paperlight.space3,
  },
  previewTarget: {
    color: paperlight.ink,
    fontWeight: 650,
  },
  previewContent: {
    color: paperlight.ink,
    fontSize: paperlight.textMd,
    lineHeight: 1.65,
  },
  previewEmpty: {
    color: paperlight.inkMuted,
    fontStyle: 'italic',
    margin: 0,
  },
  embedPanel: {
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space2,
    padding: paperlight.space3,
  },
  embedRow: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
  },
  embedInput: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusSm,
    borderStyle: 'solid',
    borderWidth: 1,
    boxSizing: 'border-box',
    color: paperlight.ink,
    flex: '1 1 16rem',
    fontFamily: paperlight.uiFont,
    fontSize: '0.9375rem',
    minHeight: paperlight.touchTarget,
    minWidth: 0,
    paddingInline: paperlight.space3,
  },
  status: {
    alignItems: 'center',
    color: paperlight.inkMuted,
    display: 'flex',
    flexWrap: 'wrap',
    fontSize: paperlight.textSm,
    gap: paperlight.space2,
    margin: 0,
  },
  statusError: {
    color: paperlight.danger,
  },
  progress: {
    accentColor: paperlight.forest,
    height: paperlight.space2,
    maxWidth: '16rem',
    width: '100%',
  },
  attachmentList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  attachment: {
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusRound,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textSm,
    maxWidth: '100%',
    overflowWrap: 'anywhere',
    paddingBlock: paperlight.space1,
    paddingInline: paperlight.space3,
  },
  attachmentLink: {
    alignItems: 'center',
    color: paperlight.forest,
    display: 'inline-flex',
    minHeight: paperlight.touchTarget,
    marginBlock: `-${paperlight.space1}`,
    marginInline: `-${paperlight.space3}`,
    maxWidth: '100%',
    overflowWrap: 'anywhere',
    paddingBlock: paperlight.space1,
    paddingInline: paperlight.space3,
  },
  compact: {
    '@media (max-width: 35rem)': {
      padding: paperlight.space3,
    },
  },
});
