/* Hallmark · project workbench styles · data views, forms, and page rhythm */

import * as stylex from '@stylexjs/stylex';
import { paperlight } from '@oss-tips/design-tokens/paperlight.stylex';

export const projectStyles = stylex.create({
  page: {
    minWidth: 0,
    width: '100%',
  },
  grid2: {
    display: 'grid',
    gap: paperlight.space6,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
  },
  grid3: {
    display: 'grid',
    gap: paperlight.space4,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
  },
  autoGrid: {
    display: 'grid',
    gap: paperlight.space4,
    gridTemplateColumns: 'repeat(auto-fit, minmax(11.5rem, 1fr))',
  },
  surface: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    minWidth: 0,
    padding: paperlight.space5,
  },
  surfaceTight: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    minWidth: 0,
    paddingBlock: paperlight.space2,
  },
  formSurface: {
    maxWidth: '36rem',
  },
  connectMount: {
    minHeight: '16rem',
    width: '100%',
  },
  connectPreview: {
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusSm,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
    justifyContent: 'center',
    minHeight: '16rem',
    padding: paperlight.space5,
  },
  connectPreviewKicker: {
    color: paperlight.inkMuted,
    fontFamily: paperlight.monoFont,
    fontSize: paperlight.textSm,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  connectPreviewStatus: {
    color: paperlight.forest,
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textMd,
    fontWeight: 650,
    margin: 0,
  },
  stack: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space4,
    minWidth: 0,
  },
  stackTight: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space2,
    minWidth: 0,
  },
  row: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
    minWidth: 0,
  },
  publicDisplayCheck: {
    alignItems: 'flex-start',
    display: 'flex',
    gap: paperlight.space2,
    minHeight: paperlight.touchTarget,
  },
  publicDisplayCheckbox: {
    accentColor: paperlight.forest,
    blockSize: '1.125rem',
    flex: '0 0 auto',
    inlineSize: '1.125rem',
    marginBlockStart: paperlight.space1,
  },
  between: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
    justifyContent: 'space-between',
  },
  section: {
    marginBlockStart: paperlight.space6,
  },
  lifecycleDanger: {
    borderBlockStart: `1px solid ${paperlight.border}`,
    marginBlockStart: paperlight.space4,
    paddingBlockStart: paperlight.space5,
  },
  sectionHeading: {
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textMd,
    fontWeight: 650,
    lineHeight: 1.2,
    margin: 0,
    minWidth: 0,
    overflowWrap: 'anywhere',
    paddingBlock: `${paperlight.space6} ${paperlight.space3}`,
  },
  cardHeading: {
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textLg,
    fontWeight: 650,
    lineHeight: 1.2,
    margin: 0,
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  body: {
    color: paperlight.ink,
    margin: 0,
  },
  muted: {
    color: paperlight.inkMuted,
  },
  small: {
    fontSize: paperlight.textSm,
  },
  micro: {
    fontSize: paperlight.textSm,
  },
  numeric: {
    fontVariantNumeric: 'tabular-nums',
  },
  linkButton: {
    alignItems: 'center',
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: paperlight.space3,
  },
  inboxList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  inboxRow: {
    alignItems: 'center',
    borderBlockEnd: `1px solid ${paperlight.border}`,
    display: 'grid',
    gap: paperlight.space3,
    gridTemplateColumns: '2.25rem minmax(0, 1fr) auto auto',
    minWidth: 0,
    paddingBlock: paperlight.space3,
  },
  inboxButton: {
    backgroundColor: 'transparent',
    borderStyle: 'none',
    borderWidth: 0,
    color: 'inherit',
    cursor: 'pointer',
    display: 'grid',
    gap: paperlight.space3,
    gridTemplateColumns: '2.25rem minmax(0, 1fr) auto',
    minWidth: 0,
    padding: `${paperlight.space3} ${paperlight.space4}`,
    textAlign: 'start',
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': paperlight.motionReduced,
    },
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: paperlight.easeOut,
    width: '100%',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: paperlight.canvasSubtle,
      },
    },
    ':active': {
      transform: 'translateY(1px) scale(0.99)',
    },
    '@media (prefers-reduced-motion: reduce)': {
      ':active': {
        transform: 'none',
      },
    },
  },
  selected: {
    backgroundColor: paperlight.canvasSubtle,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusRound,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.forest,
    display: 'flex',
    flexShrink: 0,
    fontFamily: paperlight.uiFont,
    fontWeight: 650,
    height: '2.25rem',
    justifyContent: 'center',
    width: '2.25rem',
  },
  avatarSmall: {
    height: '2rem',
    width: '2rem',
  },
  truncate: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  topSupporter: {
    alignItems: 'center',
    borderBlockEnd: `1px solid ${paperlight.border}`,
    display: 'flex',
    gap: paperlight.space3,
    justifyContent: 'space-between',
    paddingBlock: paperlight.space3,
  },
  rank: {
    color: paperlight.ink,
    fontWeight: 650,
    width: '1.5rem',
  },
  toolCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
  },
  toolBlurb: {
    flex: 1,
    fontSize: paperlight.textSm,
    margin: 0,
  },
  actionLink: {
    alignItems: 'center',
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusSm,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    display: 'inline-flex',
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textSm,
    fontWeight: 650,
    justifyContent: 'center',
    minHeight: paperlight.touchTarget,
    paddingInline: paperlight.space4,
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    transitionDuration: {
      default: paperlight.motionFast,
      '@media (prefers-reduced-motion: reduce)': paperlight.motionReduced,
    },
    transitionProperty: 'background-color, border-color, transform',
    transitionTimingFunction: paperlight.easeOut,
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: paperlight.canvasSubtle,
        borderColor: paperlight.forest,
      },
    },
    ':active': {
      transform: 'translateY(1px) scale(0.99)',
    },
    '@media (prefers-reduced-motion: reduce)': {
      ':active': {
        transform: 'none',
      },
    },
  },
  fieldLabel: {
    color: paperlight.ink,
    display: 'block',
    fontFamily: paperlight.uiFont,
    fontSize: paperlight.textSm,
    fontWeight: 650,
    marginBlockEnd: paperlight.space2,
  },
  textarea: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusSm,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    display: 'block',
    font: 'inherit',
    lineHeight: 1.5,
    minHeight: '12rem',
    padding: paperlight.space3,
    resize: 'vertical',
    width: '100%',
  },
  divider: {
    border: 0,
    borderBlockStart: `1px solid ${paperlight.border}`,
    marginBlock: paperlight.space4,
    width: '100%',
  },
  onboardingSteps: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
    listStyle: 'none',
    margin: `0 0 ${paperlight.space8}`,
    padding: 0,
  },
  chartSurface: {
    overflow: 'hidden',
  },
  chartHeader: {
    alignItems: 'flex-start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
    justifyContent: 'space-between',
    marginBlockEnd: paperlight.space3,
  },
  chartLegend: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space4,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  chartLegendItem: {
    alignItems: 'center',
    color: paperlight.ink,
    display: 'flex',
    fontSize: paperlight.textSm,
    gap: paperlight.space2,
  },
  chartLegendLine: {
    display: 'block',
    width: '1.25rem',
  },
  chart: {
    display: 'block',
    height: 'auto',
    width: '100%',
  },
  chartTable: {
    marginBlockStart: paperlight.space4,
    overflowX: 'auto',
  },
  table: {
    borderCollapse: 'collapse',
    fontSize: '0.9375rem',
    minWidth: '36rem',
    width: '100%',
  },
  tableHead: {
    backgroundColor: paperlight.canvasSubtle,
    borderBlockEnd: `1px solid ${paperlight.border}`,
    color: paperlight.ink,
    fontFamily: paperlight.uiFont,
    fontSize: '0.8125rem',
    fontWeight: 650,
    padding: `${paperlight.space3} ${paperlight.space4}`,
    textAlign: 'start',
    whiteSpace: 'nowrap',
  },
  tableCell: {
    borderBlockEnd: `1px solid ${paperlight.border}`,
    padding: `${paperlight.space3} ${paperlight.space4}`,
    textAlign: 'start',
    verticalAlign: 'top',
  },
  tableCaption: {
    captionSide: 'top',
    paddingBlockEnd: paperlight.space2,
    textAlign: 'start',
  },
  empty: {
    alignItems: 'center',
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'dashed',
    borderWidth: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space2,
    justifyContent: 'center',
    minHeight: '10rem',
    padding: paperlight.space6,
    textAlign: 'center',
  },
  error: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.danger,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    padding: paperlight.space5,
  },
  permission: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.warning,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    padding: paperlight.space5,
  },
  responsiveStack: {
    '@media (max-width: 54rem)': {
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  responsiveGrid3: {
    '@media (min-width: 35.01rem) and (max-width: 54rem)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    '@media (max-width: 35rem)': {
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  compactInboxRow: {
    '@media (max-width: 35rem)': {
      gridTemplateColumns: '2.25rem minmax(0, 1fr) auto',
    },
  },
  compactHide: {
    '@media (max-width: 35rem)': {
      display: 'none',
    },
  },
});
