/* Hallmark · pre-emit critique: P5 H5 E4 S5 R5 V4
 * Paperlight shell and navigation primitives. Responsive disclosure stays native.
 */

import * as stylex from '@stylexjs/stylex';
import { paperlight } from '@oss-tips/design-tokens/paperlight.stylex';

const sheetPanelEnter = stylex.keyframes({
  from: { opacity: 0, transform: 'translateX(-8px)' },
  to: { opacity: 1, transform: 'translateX(0)' },
});

const sheetPanelExit = stylex.keyframes({
  from: { opacity: 1, transform: 'translateX(0)' },
  to: { opacity: 0, transform: 'translateX(-8px)' },
});

// Keep StyleX calls in this sidecar so Svelte markup is left to the Svelte compiler.
export const attrs = stylex.attrs;

export const shells = stylex.create({
  skipLink: {
    backgroundColor: paperlight.ink,
    borderRadius: paperlight.radiusSm,
    color: paperlight.canvas,
    insetInlineStart: paperlight.space3,
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space3,
    position: 'fixed',
    top: paperlight.space3,
    transform: {
      default: 'translateY(calc(-100% - 2rem))',
      ':focus-visible': 'translateY(0)',
    },
    zIndex: 100,
  },
  focus: {
    outlineColor: {
      default: 'transparent',
      ':focus-visible': paperlight.focus,
    },
    outlineOffset: {
      default: 3,
      ':focus-visible': 3,
    },
    outlineStyle: {
      default: 'solid',
      ':focus-visible': 'solid',
    },
    outlineWidth: {
      default: 2,
      ':focus-visible': 2,
    },
  },
  publicNav: {
    alignItems: 'center',
    backgroundColor: paperlight.canvas,
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    fontFamily: paperlight.uiFont,
    gap: paperlight.space5,
    justifyContent: 'flex-start',
    paddingBlock: paperlight.space3,
    paddingInline: {
      default: paperlight.space6,
      '@media (max-width: 43.99rem)': paperlight.space4,
    },
    position: 'sticky',
    top: 0,
    zIndex: 20,
  },
  publicHome: {
    alignItems: 'center',
    borderRadius: paperlight.radiusSm,
    display: 'inline-flex',
    flexShrink: 0,
    minHeight: paperlight.touchTarget,
    minWidth: '6rem',
  },
  publicDesktopNav: {
    display: {
      default: 'block',
      '@media (max-width: 63.99rem)': 'none',
    },
    marginInlineEnd: 'auto',
  },
  publicLinks: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space5,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  publicLink: {
    alignItems: 'center',
    color: paperlight.inkMuted,
    display: 'inline-flex',
    fontFamily: paperlight.uiFont,
    fontSize: '0.9375rem',
    fontWeight: 500,
    minHeight: paperlight.touchTarget,
    borderRadius: paperlight.radiusSm,
    textDecoration: 'none',
    '@media (hover: hover)': {
      ':hover': {
        color: paperlight.ink,
      },
    },
  },
  publicLinkActive: {
    color: paperlight.forest,
    fontWeight: 600,
  },
  publicActions: {
    alignItems: 'center',
    display: 'flex',
    flexShrink: 0,
    gap: paperlight.space3,
  },
  publicDesktopActions: {
    display: {
      default: 'flex',
      '@media (max-width: 63.99rem)': 'none',
    },
  },
  secondaryLink: {
    alignItems: 'center',
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    display: 'inline-flex',
    fontFamily: paperlight.uiFont,
    fontSize: '0.9375rem',
    fontWeight: 600,
    justifyContent: 'center',
    minHeight: paperlight.touchTarget,
    paddingInline: paperlight.space4,
    textDecoration: 'none',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: paperlight.canvasSubtle,
        borderColor: paperlight.forest,
      },
    },
  },
  sheetActions: {
    alignItems: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
    marginTop: paperlight.space8,
  },
  mobileMenuButton: {
    alignItems: 'center',
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    cursor: 'pointer',
    display: {
      default: 'none',
      '@media (max-width: 63.99rem)': 'inline-flex',
    },
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
    fontWeight: 600,
    gap: paperlight.space2,
    justifyContent: 'center',
    minHeight: paperlight.touchTarget,
    minWidth: paperlight.touchTarget,
    marginInlineStart: 'auto',
    paddingInline: paperlight.space3,
  },
  icon: {
    display: 'block',
    flexShrink: 0,
    height: '1.125rem',
    width: '1.125rem',
  },
  sheet: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderStyle: 'solid',
    borderWidth: 0,
    color: paperlight.ink,
    height: '100dvh',
    inset: 0,
    margin: 0,
    maxHeight: 'none',
    maxWidth: '100%',
    padding: 0,
    width: '100%',
    '::backdrop': {
      backgroundColor: paperlight.overlay,
    },
  },
  sheetPanel: {
    backgroundColor: paperlight.surface,
    borderInlineEndColor: paperlight.border,
    borderInlineEndStyle: 'solid',
    borderInlineEndWidth: 1,
    boxShadow: paperlight.shadow,
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100%',
    overflowY: 'auto',
    padding: paperlight.space6,
    width: 'min(22rem, calc(100vw - 2.5rem))',
  },
  sheetPanelEnter: {
    animationName: sheetPanelEnter,
    animationDuration: {
      default: '180ms',
      '@media (prefers-reduced-motion: reduce)': '0.01ms',
    },
    animationFillMode: 'both',
    animationTimingFunction: paperlight.easeOut,
  },
  sheetPanelExit: {
    animationName: sheetPanelExit,
    animationDuration: {
      default: '180ms',
      '@media (prefers-reduced-motion: reduce)': '0.01ms',
    },
    animationFillMode: 'both',
    animationTimingFunction: paperlight.easeOut,
  },
  sheetTop: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: paperlight.space6,
  },
  sheetTitle: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: '1.5rem',
    fontWeight: 500,
    lineHeight: 1.1,
    margin: 0,
  },
  closeButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    cursor: 'pointer',
    display: 'inline-flex',
    justifyContent: 'center',
    minHeight: paperlight.touchTarget,
    minWidth: paperlight.touchTarget,
    padding: 0,
  },
  dashboard: {
    backgroundColor: paperlight.canvas,
    display: 'flex',
    minHeight: '100vh',
    minWidth: 0,
    width: '100%',
  },
  admin: {
    backgroundColor: paperlight.canvas,
    display: 'flex',
    minHeight: '100vh',
    minWidth: 0,
    width: '100%',
  },
  sidebar: {
    alignSelf: 'flex-start',
    backgroundColor: paperlight.surface,
    borderRightColor: paperlight.border,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    display: {
      default: 'block',
      '@media (max-width: 43.99rem)': 'none',
    },
    flexShrink: 0,
    minHeight: '100vh',
    paddingBlock: paperlight.space6,
    position: 'sticky',
    top: 0,
    width: paperlight.sidebar,
  },
  brand: {
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    marginBottom: paperlight.space2,
    paddingBottom: paperlight.space5,
    paddingInline: paperlight.space4,
  },
  overline: {
    color: paperlight.inkMuted,
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    margin: 0,
    textTransform: 'uppercase',
  },
  project: {
    color: paperlight.ink,
    display: 'block',
    fontFamily: paperlight.uiFont,
    fontSize: '1.125rem',
    fontWeight: 600,
    marginTop: paperlight.space1,
  },
  sidebarNav: {
    margin: 0,
    padding: 0,
  },
  sidebarGroup: {
    color: paperlight.inkMuted,
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space4,
    textTransform: 'uppercase',
  },
  sidebarList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  sidebarLink: {
    alignItems: 'center',
    borderLeftColor: 'transparent',
    borderLeftStyle: 'solid',
    borderLeftWidth: 3,
    color: paperlight.ink,
    display: 'flex',
    fontFamily: paperlight.uiFont,
    fontSize: '0.9375rem',
    fontWeight: 500,
    gap: paperlight.space2,
    minHeight: paperlight.touchTarget,
    paddingBlock: paperlight.space2,
    paddingInline: paperlight.space4,
    textDecoration: 'none',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: paperlight.canvasSubtle,
      },
    },
  },
  sidebarActive: {
    backgroundColor: paperlight.canvasSubtle,
    borderLeftColor: paperlight.forest,
    color: paperlight.forest,
  },
  sidebarAdminActive: {
    backgroundColor: paperlight.canvasSubtle,
    borderLeftColor: paperlight.info,
    color: paperlight.info,
  },
  adminAccent: {
    color: paperlight.info,
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
    fontWeight: 600,
    margin: 0,
  },
  adminSub: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    marginTop: paperlight.space1,
    marginBottom: 0,
  },
  main: {
    flex: 1,
    minWidth: 0,
    paddingBlock: {
      default: paperlight.space6,
      '@media (max-width: 43.99rem)': paperlight.space4,
    },
    paddingInline: {
      default: paperlight.space8,
      '@media (max-width: 43.99rem)': paperlight.space4,
    },
    width: '100%',
  },
  mobileBar: {
    display: {
      default: 'none',
      '@media (max-width: 43.99rem)': 'flex',
    },
    marginBottom: paperlight.space4,
  },
  mobileTrigger: {
    alignItems: 'center',
    backgroundColor: paperlight.surface,
    borderColor: paperlight.borderStrong,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
    fontWeight: 600,
    gap: paperlight.space2,
    minHeight: paperlight.touchTarget,
    paddingInline: paperlight.space3,
  },
  header: {
    marginBottom: paperlight.space6,
  },
  title: {
    color: paperlight.ink,
    fontFamily: paperlight.uiFont,
    fontSize: '1.75rem',
    fontWeight: 600,
    letterSpacing: '-0.01em',
    margin: 0,
  },
  lede: {
    color: paperlight.inkMuted,
    fontFamily: paperlight.uiFont,
    marginTop: paperlight.space2,
    maxWidth: '36rem',
  },
  context: {
    color: paperlight.inkMuted,
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
    fontWeight: 500,
    marginBottom: paperlight.space2,
  },
  footer: {
    backgroundColor: paperlight.canvasSubtle,
    borderTopColor: paperlight.border,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingBottom: paperlight.space10,
  },
  footerLandscape: {
    marginBottom: paperlight.space8,
  },
  footerMasthead: {
    alignItems: 'start',
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    flexDirection: {
      default: 'row',
      '@media (max-width: 43.99rem)': 'column',
    },
    gap: {
      default: paperlight.space10,
      '@media (max-width: 43.99rem)': paperlight.space6,
    },
    justifyContent: 'space-between',
    paddingBottom: paperlight.space8,
  },
  footerCopy: {
    alignItems: 'flex-start',
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space3,
    maxWidth: '32rem',
  },
  footerStrapline: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: '1.5rem',
    lineHeight: 1.15,
    margin: 0,
  },
  footerLead: {
    color: paperlight.inkMuted,
    fontSize: '0.9375rem',
    marginBottom: 0,
    marginTop: 0,
    maxWidth: '28rem',
  },
  footerNav: {
    display: 'grid',
    gap: paperlight.space8,
    gridTemplateColumns: 'repeat(2, minmax(7rem, 1fr))',
    minWidth: {
      default: '16rem',
      '@media (max-width: 43.99rem)': 0,
    },
  },
  footerGroup: {
    minWidth: 0,
  },
  footerHeading: {
    color: paperlight.ink,
    display: 'block',
    fontFamily: paperlight.uiFont,
    fontSize: '0.875rem',
    fontWeight: 700,
    letterSpacing: '0.04em',
    marginBottom: paperlight.space2,
    textTransform: 'uppercase',
  },
  footerLinks: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space1,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  footerLink: {
    alignItems: 'center',
    color: paperlight.inkMuted,
    display: 'inline-flex',
    fontSize: '0.875rem',
    minHeight: paperlight.touchTarget,
  },
  footerLegal: {
    alignItems: {
      default: 'center',
      '@media (max-width: 43.99rem)': 'flex-start',
    },
    color: paperlight.inkMuted,
    display: 'flex',
    fontSize: '0.875rem',
    gap: {
      default: paperlight.space3,
      '@media (max-width: 43.99rem)': paperlight.space2,
    },
    flexDirection: {
      default: 'row',
      '@media (max-width: 43.99rem)': 'column',
    },
    justifyContent: 'space-between',
    margin: 0,
    paddingTop: paperlight.space4,
  },
  footerLegalLink: {
    color: paperlight.inkMuted,
    minHeight: paperlight.touchTarget,
    display: 'inline-flex',
    alignItems: 'center',
  },
});
