/* Hallmark · Paperlight supporter workspace recipes */

import * as stylex from '@stylexjs/stylex';
import { paperlight } from '@oss-tips/design-tokens/paperlight.stylex';

export const supporter = stylex.create({
  page: {
    backgroundColor: paperlight.canvas,
    color: paperlight.ink,
    minHeight: '100vh',
  },
  container: {
    marginInline: 'auto',
    maxWidth: paperlight.contentMax,
    paddingBlock: paperlight.space12,
    paddingInline: paperlight.space6,
    width: '100%',
    '@media (max-width: 43.99rem)': {
      paddingBlock: paperlight.space8,
      paddingInline: paperlight.space4,
    },
  },
  reading: {
    maxWidth: paperlight.readingMax,
  },
  header: {
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    marginBottom: paperlight.space8,
    paddingBottom: paperlight.space6,
  },
  eyebrow: {
    color: paperlight.forest,
    fontFamily: paperlight.monoFont,
    fontSize: '0.875rem',
    fontWeight: 600,
    letterSpacing: '0.04em',
    margin: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: 'clamp(2.25rem, 5vw, 3.75rem)',
    fontWeight: 500,
    letterSpacing: '-0.035em',
    lineHeight: 1.02,
    marginBlock: `${paperlight.space2} 0`,
  },
  lede: {
    color: paperlight.inkMuted,
    fontFamily: paperlight.uiFont,
    fontSize: '1.125rem',
    lineHeight: 1.5,
    marginBlock: `${paperlight.space3} 0`,
    maxWidth: '44rem',
  },
  accountNav: {
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    marginBlock: `${paperlight.space6} ${paperlight.space8}`,
  },
  accountNavList: {
    display: 'flex',
    flexWrap: 'wrap',
    rowGap: paperlight.space1,
    columnGap: paperlight.space2,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  accountLink: {
    alignItems: 'center',
    borderBottomColor: 'transparent',
    borderBottomStyle: 'solid',
    borderBottomWidth: 2,
    borderRadius: paperlight.radiusSm,
    color: paperlight.inkMuted,
    display: 'inline-flex',
    fontFamily: paperlight.uiFont,
    fontSize: '0.9375rem',
    fontWeight: 600,
    minHeight: paperlight.touchTarget,
    paddingInline: paperlight.space3,
    textDecoration: 'none',
    transitionDuration: paperlight.motionFast,
    transitionProperty: 'color, border-color, background-color',
    transitionTimingFunction: paperlight.easeOut,
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: paperlight.canvasSubtle,
        color: paperlight.ink,
        textDecoration: 'none',
      },
    },
    ':focus-visible': {
      outlineColor: paperlight.focus,
      outlineOffset: 3,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0.01ms',
    },
  },
  accountLinkActive: {
    borderBottomColor: paperlight.forest,
    color: paperlight.ink,
  },
  summaryGrid: {
    display: 'grid',
    gap: paperlight.space4,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    marginBottom: paperlight.space6,
    '@media (max-width: 50rem)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    '@media (max-width: 33rem)': {
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  section: {
    marginBlock: `${paperlight.space10} 0`,
  },
  sectionTitle: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: '1.5rem',
    fontWeight: 500,
    lineHeight: 1.1,
    margin: 0,
  },
  sectionIntro: {
    color: paperlight.inkMuted,
    fontSize: '0.9375rem',
    lineHeight: 1.5,
    marginBlock: `${paperlight.space2} ${paperlight.space4}`,
  },
  surface: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    padding: paperlight.space5,
  },
  surfaceTitle: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: '1.35rem',
    fontWeight: 500,
    lineHeight: 1.15,
    margin: 0,
  },
  row: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
  },
  rowBetween: {
    alignItems: 'flex-start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space4,
    justifyContent: 'space-between',
  },
  muted: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
  },
  rule: {
    border: 0,
    borderTopColor: paperlight.border,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    marginBlock: paperlight.space8,
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: paperlight.space6,
    marginTop: paperlight.space4,
  },
  fieldNote: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    lineHeight: 1.45,
    margin: `${paperlight.space2} 0 0`,
  },
  inboxLayout: {
    display: 'grid',
    gap: paperlight.space6,
    gridTemplateColumns: 'minmax(12rem, 0.8fr) minmax(0, 1.5fr)',
    '@media (max-width: 50rem)': {
      gridTemplateColumns: 'minmax(0, 1fr)',
    },
  },
  inboxList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  inboxListItem: {
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  inboxItem: {
    alignItems: 'stretch',
    backgroundColor: 'transparent',
    border: 0,
    borderRadius: paperlight.radiusMd,
    color: paperlight.ink,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: paperlight.uiFont,
    gap: paperlight.space2,
    paddingBlock: paperlight.space4,
    paddingInline: paperlight.space2,
    textAlign: 'start',
    transitionDuration: paperlight.motionFast,
    transitionProperty: 'background-color, transform',
    transitionTimingFunction: paperlight.easeOut,
    width: '100%',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: paperlight.canvasSubtle,
      },
    },
    ':focus-visible': {
      outlineColor: paperlight.focus,
      outlineOffset: 3,
      outlineStyle: 'solid',
      outlineWidth: 2,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0.01ms',
    },
  },
  inboxItemSelected: {
    backgroundColor: paperlight.canvasSubtle,
    boxShadow: `inset 0 0 0 1px ${paperlight.borderStrong}`,
    paddingInline: paperlight.space3,
  },
  feedList: {
    display: 'grid',
    gap: paperlight.space6,
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  feedCard: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'solid',
    borderWidth: 1,
    display: 'grid',
    gap: paperlight.space5,
    padding: paperlight.space5,
  },
  feedCardHeader: {
    alignItems: 'flex-start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space4,
    justifyContent: 'space-between',
  },
  feedProject: {
    color: paperlight.forest,
    display: 'inline-block',
    fontFamily: paperlight.monoFont,
    fontSize: '0.8125rem',
    fontWeight: 600,
    letterSpacing: '0.03em',
    textDecoration: 'none',
    textTransform: 'uppercase',
  },
  feedTitle: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: '1.75rem',
    fontWeight: 500,
    lineHeight: 1.08,
    marginBlock: `${paperlight.space2} 0`,
  },
  feedMeta: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    margin: `${paperlight.space2} 0 0`,
  },
  feedBody: {
    fontSize: '1.0625rem',
    lineHeight: 1.65,
    overflowWrap: 'anywhere',
  },
  feedAttachments: {
    borderTopColor: paperlight.border,
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    paddingTop: paperlight.space4,
  },
  feedAttachmentList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
    listStyle: 'none',
    margin: `${paperlight.space3} 0 0`,
    padding: 0,
  },
  feedAttachment: {
    color: paperlight.forest,
    fontSize: '0.9375rem',
    fontWeight: 600,
  },
  inboxMeta: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
    justifyContent: 'space-between',
    width: '100%',
  },
  error: {
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.danger,
    borderRadius: paperlight.radiusMd,
    borderStyle: 'solid',
    borderWidth: 1,
    color: paperlight.ink,
    marginBlock: paperlight.space6,
    padding: paperlight.space4,
  },
  empty: {
    backgroundColor: paperlight.canvasSubtle,
    borderColor: paperlight.border,
    borderRadius: paperlight.radiusLg,
    borderStyle: 'dashed',
    borderWidth: 1,
    color: paperlight.inkMuted,
    paddingBlock: paperlight.space8,
    paddingInline: paperlight.space5,
    textAlign: 'center',
  },
  emptyTitle: {
    color: paperlight.ink,
    fontFamily: paperlight.displayFont,
    fontSize: '1.35rem',
    fontWeight: 500,
    margin: 0,
  },
  emptyCopy: {
    margin: `${paperlight.space2} 0 0`,
  },
  statusLine: {
    alignItems: 'flex-start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space2,
    lineHeight: 1.5,
    marginBlock: `${paperlight.space3} 0`,
  },
  securityList: {
    listStyle: 'none',
    margin: `${paperlight.space4} 0 0`,
    padding: 0,
  },
  securityItem: {
    alignItems: 'flex-start',
    borderBottomColor: paperlight.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space4,
    justifyContent: 'space-between',
    paddingBlock: paperlight.space4,
  },
  securityItemLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  securityCopy: {
    minWidth: '12rem',
  },
  securityLabel: {
    color: paperlight.ink,
    display: 'block',
    fontWeight: 600,
  },
  securityMeta: {
    color: paperlight.inkMuted,
    fontSize: '0.875rem',
    lineHeight: 1.45,
    margin: `${paperlight.space1} 0 0`,
  },
  securityForm: {
    alignItems: 'flex-end',
    display: 'flex',
    flexWrap: 'wrap',
    gap: paperlight.space3,
    marginTop: paperlight.space5,
  },
});
