/* Documentation snapshot. Runtime source: packages/design-tokens/src/paperlight.stylex.ts. */
import * as stylex from '@stylexjs/stylex';

/** Generated starting point for the oss.tips Paperlight design system. */
export const paperlight = stylex.defineVars({
  canvas: '#FBF7EF',
  canvasSubtle: '#F5EFE4',
  surface: '#FFFDF8',
  surfaceRaised: '#F4EEDF',
  ink: '#1E2A22',
  inkMuted: '#5C665B',
  inkFaint: '#61685F',
  forest: '#2D5C3A',
  forestHover: '#244A30',
  moss: '#7C8A5B',
  fern: '#A8B59A',
  ochre: '#B88747',
  border: '#DDD5C6',
  borderStrong: '#918878',
  success: '#2F6A41',
  warning: '#9A651F',
  danger: '#A3463C',
  info: '#366A76',
  focus: '#2D5C3A',
  overlay: 'rgba(30, 42, 34, .46)',
  displayFont: "Newsreader, 'EB Garamond', Georgia, serif",
  uiFont: "'Source Sans 3', Inter, system-ui, sans-serif",
  monoFont: "'IBM Plex Mono', 'JetBrains Mono', ui-monospace, monospace",
  radiusSm: '6px',
  radiusMd: '10px',
  radiusLg: '14px',
  radiusXl: '20px',
  shadow: '0 1px 2px rgba(30,42,34,.06), 0 12px 32px rgba(30,42,34,.07)',
  motionFast: '140ms',
  motionNormal: '220ms',
  easeStandard: 'cubic-bezier(.2,.8,.2,1)',
});

export const paperlightDark = stylex.createTheme(paperlight, {
  canvas: '#11130F',
  canvasSubtle: '#151813',
  surface: '#171A15',
  surfaceRaised: '#1D211B',
  ink: '#EDE7D8',
  inkMuted: '#B4B1A3',
  inkFaint: '#8E9084',
  forest: '#91A66E',
  forestHover: '#A5BA82',
  moss: '#71834F',
  fern: '#4D5E3C',
  ochre: '#C6A36B',
  border: '#34382E',
  borderStrong: '#626858',
  success: '#A5C87D',
  warning: '#D8B06C',
  danger: '#D47A6E',
  info: '#8AADA6',
  focus: '#B5CF8D',
  overlay: 'rgba(0,0,0,.64)',
  shadow: '0 1px 2px rgba(0,0,0,.32), 0 16px 40px rgba(0,0,0,.22)',
});

export const primitives = stylex.create({
  focusRing: {
    outline: `2px solid ${paperlight.focus}`,
    outlineOffset: '3px',
  },
  card: {
    backgroundColor: paperlight.surface,
    borderColor: paperlight.border,
    borderStyle: 'solid',
    borderWidth: '1px',
    borderRadius: paperlight.radiusLg,
    boxShadow: paperlight.shadow,
  },
  buttonPrimary: {
    minHeight: '44px',
    paddingBlock: '10px',
    paddingInline: '18px',
    borderRadius: paperlight.radiusMd,
    backgroundColor: {
      default: paperlight.forest,
      ':hover': paperlight.forestHover,
    },
    color: paperlight.canvas,
    fontFamily: paperlight.uiFont,
    fontWeight: 650,
    transitionProperty: 'transform, background-color, box-shadow',
    transitionDuration: paperlight.motionFast,
    transitionTimingFunction: paperlight.easeStandard,
    transform: { ':active': 'translateY(1px) scale(.99)' },
  },
});
